
import java.awt.Color;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * About.java
 *
 * Created on Apr 5, 2018, 3:52:33 PM
 */

/**
 *
 * @author ok
 */
public class About extends javax.swing.JFrame {

    /** Creates new form About */
    public About() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectView = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pp6 = new javax.swing.JPanel();
        c10 = new javax.swing.JCheckBox();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        c8 = new javax.swing.JCheckBox();
        c9 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        pp7 = new javax.swing.JPanel();
        c11 = new javax.swing.JCheckBox();
        c12 = new javax.swing.JCheckBox();
        c13 = new javax.swing.JCheckBox();
        c14 = new javax.swing.JCheckBox();
        pp8 = new javax.swing.JPanel();
        c15 = new javax.swing.JCheckBox();
        c16 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        ProjectView.setMinimumSize(new java.awt.Dimension(800, 650));
        ProjectView.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                ProjectViewWindowOpened(evt);
            }
        });
        ProjectView.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextArea1.setRows(5);
        jTextArea1.setText("   Hello Everyone !\n\tThis Bank Module project helps in maintaining Account_holder's data efficiently and\n \tprovide Account_holder's with various type of facilities which make's it convinient\n\tfor them to perform banking tasks easily . ");
        jTextArea1.setBorder(new javax.swing.border.MatteBorder(null));
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        ProjectView.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 580, 90));

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setText("Accountant Control");
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder("Click me:"));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        ProjectView.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 160, 60));

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton4.setText("Facilities to User");
        jButton4.setBorder(javax.swing.BorderFactory.createTitledBorder("Click me:"));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        ProjectView.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 160, 60));

        pp6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c10.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c10.setText("MOBILE RECHARGE");
        pp6.add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, -1));

        c1.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c1.setText("CASH WITHDRAW");
        pp6.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        c2.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c2.setText("DEPOSIT MONEY");
        pp6.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, -1));

        c3.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c3.setText("BALANCE CHECK");
        pp6.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, -1));

        c4.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c4.setText("USER INFO");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        pp6.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, -1));

        c5.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c5.setText("APPLY FOR LOAN");
        pp6.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        c6.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c6.setText("STATUS OF LOAN (IF LOAN TAKEN)");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        pp6.add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 270, -1));

        c7.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c7.setText("MONEY TRANSFER");
        pp6.add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, -1));

        c8.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c8.setText("TRANSACTION DETAILS");
        pp6.add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, -1));

        c9.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c9.setText("AADHAAR  CARD LINK");
        pp6.add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 190, -1));

        ProjectView.getContentPane().add(pp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 280, 310));

        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton5.setText("Manager Control");
        jButton5.setBorder(javax.swing.BorderFactory.createTitledBorder("Click me:"));
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ProjectView.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 160, 60));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        ProjectView.getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 20, 450));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        ProjectView.getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 20, 440));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        ProjectView.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 20, 70, 30));

        pp7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c11.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c11.setText("ALL ACCOUNT DETAILS");
        pp7.add(c11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, -1));

        c12.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c12.setText("USER_CONTROL");
        pp7.add(c12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, -1));

        c13.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c13.setText("LOAN DETAILS");
        pp7.add(c13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, -1));

        c14.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c14.setText("LOAN APPLICATIONS");
        pp7.add(c14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, -1));

        ProjectView.getContentPane().add(pp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 200, 250));

        pp8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c15.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c15.setText("<html>TRANSACTION  DETAILS<br>OF ALL ACCOUNTS</HTML>");
        pp8.add(c15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 40));

        c16.setFont(new java.awt.Font("Times New Roman", 3, 14));
        c16.setText("LOAN DETAILS");
        c16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c16ActionPerformed(evt);
            }
        });
        pp8.add(c16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, -1));

        ProjectView.getContentPane().add(pp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 200, 130));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("2017 - 18");
        jLabel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SESSION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("VI");
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEMESTER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, 50));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MR. RAMRATAN AHIRWAR SIR");
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Submitted to :\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 260, 70));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html>AYUSH SHRIVASTAVA<BR>ADITYA DIXIT<BR>SAJAL CHOURASIYA</html>");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CREATED BY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 260, 90));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MR. SATISH PAWAR SIR");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Guidance of", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 210, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PROJECT OVERVIEW");
        jButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLICK ME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fall-163496_1280.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ProjectView.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c4ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c6ActionPerformed

    private void ProjectViewWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ProjectViewWindowOpened
        // TODO add your handling code here:
        ProjectView.getContentPane().setBackground(Color.WHITE);
        pp6.setVisible(false);
pp7.setVisible(false);
pp8.setVisible(false);
    }//GEN-LAST:event_ProjectViewWindowOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        pp6.setVisible(true);
        c1.setSelected(true);
        c2.setSelected(true);
        c3.setSelected(true);
        c4.setSelected(true);
        c5.setSelected(true);
        c6.setSelected(true);
        c7.setSelected(true);
        c8.setSelected(true);
        c9.setSelected(true);
        c10.setSelected(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ProjectView.dispose();
        new About().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         pp7.setVisible(true);
        c11.setSelected(true);
        c12.setSelected(true);
        c13.setSelected(true);
        c14.setSelected(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pp8.setVisible(true);
        c15.setSelected(true);
        c16.setSelected(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void c16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c16ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ProjectView;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c10;
    private javax.swing.JCheckBox c11;
    private javax.swing.JCheckBox c12;
    private javax.swing.JCheckBox c13;
    private javax.swing.JCheckBox c14;
    private javax.swing.JCheckBox c15;
    private javax.swing.JCheckBox c16;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox c9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pp6;
    private javax.swing.JPanel pp7;
    private javax.swing.JPanel pp8;
    // End of variables declaration//GEN-END:variables

}
