
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Account1.java
 *
 * Created on Apr 5, 2018, 3:32:53 PM
 */

/**
 *
 * @author ok
 */
public class Account1 extends javax.swing.JFrame {

    /** Creates new form Account1 */
    public Account1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tk = new javax.swing.JTextField();
        jsc = new javax.swing.JScrollPane();
        TABLE_1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ll1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images(83).jpg"))); // NOI18N
        jButton1.setText("SHOW TRANSACTIONS");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 240, 70));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("ENTER ACCOUNT NO :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, 20));
        getContentPane().add(tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 90, 20));

        TABLE_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "AMOUNT", "TYPE", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TABLE_1.setToolTipText("SHOWING YOUR PREVIOUS TRANSACTIONS");
        TABLE_1.setMinimumSize(new java.awt.Dimension(450, 350));
        jsc.setViewportView(TABLE_1);

        getContentPane().add(jsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 550, 160));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 60, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        ll1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yrs.jpg"))); // NOI18N
        getContentPane().add(ll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con =null;
                Statement stmt=null;
                ResultSet rs=null;
int ac;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) TABLE_1.getModel();
          
        int rows=model.getRowCount();
        if(rows>0) {
            for(int i=0;i<rows;i++) {
                model.removeRow(0);
            }
        }
         try {
Class.forName("java.sql.Driver");
con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmodule","root","123");
stmt=null;
rs=null;
stmt=con.createStatement();
String a=tk.getText();
String x="Select * from transaction where accountno='"+a+"'";
rs=stmt.executeQuery(x);
ll1.setVisible(true);
while(rs.next())
{
String type=rs.getString("type");
String dot=rs.getString("dot");
String amt=rs.getString("amt");
String num=rs.getString("num");

model.addRow(new Object[]{dot,amt,type,num});
 ((DefaultTableCellRenderer) TABLE_1.getTableHeader().getDefaultRenderer())
                            .setHorizontalAlignment((int)JLabel.CENTER_ALIGNMENT);
                    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                    centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                   TABLE_1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                    for(int y = 0;y<TABLE_1.getColumnCount();y++){
                        TABLE_1.getColumnModel().getColumn(y).setCellRenderer(centerRenderer);

                    }
}
con.close();
stmt.close();
}

       catch (Exception e)
       {
        JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY or ACCOUNT_NO DOES'NT EXIST");


         }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Account0().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)TABLE_1.getModel();
        int rows=model.getRowCount();
        if(rows>0) {
            for(int i=0;i<rows;i++) {
                model.removeRow(0);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
            this.getContentPane().setBackground(Color.WHITE);
            ll1.setVisible(false);
             TABLE_1.setOpaque(false);
      ((DefaultTableCellRenderer)TABLE_1.getDefaultRenderer(Object.class)).setOpaque(false);
      jsc.setOpaque(false);
      jsc.getViewport().setOpaque(false);
      TABLE_1.getTableHeader().setBackground(Color.WHITE);
      TABLE_1.getTableHeader().setFont(new Font("Batang",Font.BOLD,16));
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLE_1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jsc;
    private javax.swing.JLabel ll1;
    private javax.swing.JTextField tk;
    // End of variables declaration//GEN-END:variables

}
