import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Timer;
import javax.swing.JOptionPane;
class stoptimer
{
    static Timer t;
    public static void send(ActionListener e)
    {
         t= new Timer(100,e);
        t.start();
    }
    public static void stopt()
    {
        t.stop();
            }}
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Loading.java
 *
 * Created on Apr 4, 2018, 12:02:42 PM
 */

/**
 *
 * @author ok
 */
public class Loading extends javax.swing.JFrame {

    /** Creates new form Loading */
    public Loading() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l2 = new javax.swing.JLabel();
        pb = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOADING");
        setBounds(new java.awt.Rectangle(150, 150, 300, 300));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        l2.setToolTipText("loading");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 140, 20));

        pb.setForeground(new java.awt.Color(51, 51, 51));
        pb.setToolTipText("Files loading");
        getContentPane().add(pb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 190, 20));

        jLabel1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animated-gifs-welcome-53.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 210, 30));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coin1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con =null;
Statement stmt=null;
ResultSet rs=null;
int t=0,wp=0;
boolean check=true,check1=true;

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmodule", "root", "123");
            stmt = con.createStatement();
            String dd1 = "use bankmodule;";
            stmt.executeUpdate(dd1);
            ActionListener b = new ActionListener() {
        public void actionPerformed(ActionEvent e) {
                pb.setValue(t);
             
                t++;

                l2.setText("" + t+" % COMPLETED" );
               
                if (t == 100) {
                    stoptimer.stopt();
                    new Welcome().setVisible(true);
                    l2.setText("100 % COMPLETED");
                    pb.setVisible(false);
                    l2.setVisible(false);
                   dispose();
                }
                }
        };
        stoptimer.send(b);
        con.close();
stmt.close();
        }
       catch(ClassNotFoundException ex1)
            {
                check=false;
            } 
        catch (SQLException ex1)
        {
                check=false;
        }

        if(check==false)
        {
            try{
               Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", "123");
            stmt = con.createStatement();
          String dd = "create database bankmodule;";
            stmt.execute(dd);
            String dd1 = "use bankmodule;";
            stmt.executeUpdate(dd1);
            String q = "create table manager(Id varchar(5),password varchar(20),name varchar(10));";
            stmt.executeUpdate(q);
            String id = "A123";
            String password = "12345";
            String name = "AYUSH";

            String q1 = "Insert into manager values('"+ id +"','"+ password +"','"+ name +"')";
            stmt.executeUpdate(q1);
            String q2 = "create table accountant(Id varchar(5),password varchar(20),name varchar(10));";
            stmt.executeUpdate(q2);
            String id1 = "S123";
            String password1 = "0000";
            String name1 = "ACCOUNTANT";

            String q3 = "Insert into accountant values('"+ id1 +"','"+ password1 +"','"+ name1 +"')";
            stmt.executeUpdate(q3);

            String qq = "create table account(accountno int(5) primary key,name varchar(30),gender varchar(6),age int(3),dob date,state varchar(30),city varchar(20),contactno mediumtext);";
            stmt.executeUpdate(qq);
            String qq1 = "create table balance(accountno int(5),balance int(10));";
            stmt.executeUpdate(qq1);
            String def = "NOT LINKED";
            String qq2 = "create table login(accountno int(5),password int(4),status varchar(10),name varchar(30),aadharno varchar(10) default '"+def+"'  );";
            stmt.executeUpdate(qq2);
            String qq3 = "create table transaction(accountno varchar(5),type varchar(20),dot date,amt int(6),num varchar(20));";
            stmt.executeUpdate(qq3);
            String def1 = "NOT APPLIED";
            int def2 = 0;
            String qq4 = "create table loan(accountno varchar(5),name varchar(50),dot date,status varchar(20) default '"+def1+"',amount int(10) default '"+def2+"' );";
            stmt.executeUpdate(qq4);

            ActionListener b = new ActionListener() {
        public void actionPerformed(ActionEvent e) {

                pb.setValue(t);
                t++;
                l2.setText("" + t+" % COMPLETED" );
                if (t == 100) {
                    stoptimer.stopt();
                   new Welcome().setVisible(true);
                    l2.setText("100 % COMPLETED");
                    pb.setVisible(false);
                    l2.setVisible(false);
                    dispose();
                }
                }
        };
        stoptimer.send(b);
            } 
            catch (Exception ex)
            {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l2;
    private javax.swing.JProgressBar pb;
    // End of variables declaration//GEN-END:variables

}
