import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManAcc.java
 *
 * Created on Apr 4, 2018, 5:17:29 PM
 */

/**
 *
 * @author ok
 */
public class ManAcc extends javax.swing.JFrame {

    /** Creates new form ManAcc */
    public ManAcc() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        jsc = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        rb2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-50.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-50.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 50, 50));

        rb1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rb1.setText("ALL ACCOUNTS");
        rb1.setBorder(null);
        rb1.setContentAreaFilled(false);
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 150, 40));

        tb1.setBackground(new java.awt.Color(204, 204, 204));
        tb1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account_No.", "Name", "Age", "State", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb1.setGridColor(new java.awt.Color(0, 0, 0));
        tb1.setOpaque(false);
        jsc.setViewportView(tb1);

        getContentPane().add(jsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 590, 190));

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rb2.setText("SEARCH BY ACCOUNT_NO.");
        rb2.setContentAreaFilled(false);
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 210, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.setToolTipText("Clear table");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 140, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton2.setToolTipText("<< Back");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 60, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images(72).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con =null;
                Statement stmt=null;
                ResultSet rs=null;
int ac;
    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
        if (rb1.isSelected()==true){

            DefaultTableModel model = (DefaultTableModel)tb1.getModel();
            int rows=model.getRowCount();

            if(rows>0) {
                for(int i=0;i<rows;i++) {
                    model.removeRow(0);
                }
            }
            try {
                Class.forName("java.sql.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmodule","root","123");
                stmt=null;
                rs=null;
                stmt=con.createStatement();
                String x ="Select * from account";
                rs=stmt.executeQuery(x);
                while(rs.next()) {
                    ac=rs.getInt("accountno");
                    String nm=rs.getString("name").toUpperCase();
                    int age=rs.getInt("age");
                    String st=rs.getString("state").toUpperCase();
                    String ct=rs.getString("city").toUpperCase();
                    model.addRow(new Object[]{ac,nm,age,st,ct});
                    ((DefaultTableCellRenderer) tb1.getTableHeader().getDefaultRenderer())
                            .setHorizontalAlignment((int)JLabel.CENTER_ALIGNMENT);
                    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                    centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                    tb1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                    for(int y = 0;y<tb1.getColumnCount();y++){
                        tb1.getColumnModel().getColumn(y).setCellRenderer(centerRenderer);
                    }
                    
                }
                con.close();
stmt.close();
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
                }
        }



    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
        if (rb2.isSelected()==true){
            String response = JOptionPane.showInputDialog(this,"Account NO.","Enter Account NO.",JOptionPane.INFORMATION_MESSAGE);
            int a = Integer.parseInt(response);
            DefaultTableModel model = (DefaultTableModel)tb1.getModel();
            int rows=model.getRowCount();
            if(rows>0) {
                for(int i=0;i<rows;i++) {
                    model.removeRow(0);
                }
            }
            try {
                Class.forName("java.sql.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmodule","root","123");
                stmt=null;
                rs=null;
                stmt=con.createStatement();
                String x ="Select * from account where accountno='"+a+"'";
                rs=stmt.executeQuery(x);
                while(rs.next()) {
                    ac=rs.getInt("accountno");
                    String nm=rs.getString("name").toUpperCase();
                    int age=rs.getInt("age");
                    String st=rs.getString("state").toUpperCase();
                    String ct=rs.getString("city").toUpperCase();

                    model.addRow(new Object[]{ac,nm,age,st,ct});
                }
                if(ac != a ) {
                    JOptionPane.showMessageDialog(null,"ACCOUNT NO.DOES NOT EXIST");
                }
                con.close();
stmt.close();
            }

            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
                    }
             }
    }//GEN-LAST:event_rb2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)tb1.getModel();
        int rows=model.getRowCount();
        if(rows>0) {
            for(int i=0;i<rows;i++) {
                model.removeRow(0);
            }
        }        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Manager1().setVisible(true);
        dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.WHITE);
      tb1.setOpaque(false);
      ((DefaultTableCellRenderer)tb1.getDefaultRenderer(Object.class)).setOpaque(false);
      jsc.setOpaque(false);
      jsc.getViewport().setOpaque(false);
      tb1.getTableHeader().setBackground(Color.WHITE);
      tb1.getTableHeader().setFont(new Font("Batang",Font.BOLD,16));
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManAcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jsc;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables

}
