import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManLoan.java
 *
 * Created on Apr 5, 2018, 1:11:58 AM
 */

/**
 *
 * @author ok
 */
public class ManLoan extends javax.swing.JFrame {

    /** Creates new form ManLoan */
    public ManLoan() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        manb = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jsc = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        rb3 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        l1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        manb.setContentAreaFilled(false);
        manb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manbActionPerformed(evt);
            }
        });
        getContentPane().add(manb, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 50, 50));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images(83).jpg"))); // NOI18N
        jButton1.setText("  GET  DETAILS");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 190, 70));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account_No.", "Name", "Loan_Amount", "Date of Approval"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb1.setOpaque(false);
        jsc.setViewportView(tb1);

        getContentPane().add(jsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 730, 230));

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 90, 30));

        buttonGroup1.add(rb3);
        rb3.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        rb3.setText("REJECTED");
        rb3.setContentAreaFilled(false);
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        getContentPane().add(rb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        rb1.setText("APPROVED");
        rb1.setContentAreaFilled(false);
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        rb2.setText("PENDING");
        rb2.setContentAreaFilled(false);
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\bank\\images(29).jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 360, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con =null;
                Statement stmt=null;
                ResultSet rs=null;
int ac;
String st;
private void manbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manbActionPerformed
        // TODO add your handling code here:
        new Manager1().setVisible(true);
        dispose();
}//GEN-LAST:event_manbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tb1.getModel();
            int rows=model.getRowCount();

            if(rows>0) {
                for(int i=0;i<rows;i++) {
                    model.removeRow(0);
                }
            }
            try {
                Class.forName("java.sql.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmodule","root","123");
                stmt=null;
                rs=null;
                stmt=con.createStatement();
                String x ="Select * from loan where status = '"+st+"'";
               
                
                rs=stmt.executeQuery(x);
                while(rs.next()) {
                    ac=rs.getInt("accountno");
                    String nm=rs.getString("name");
                    String am=rs.getString("amount");
                    String dt=rs.getString("dot");
                    model.addRow(new Object[]{ac,nm,am,dt});
                    ((DefaultTableCellRenderer) tb1.getTableHeader().getDefaultRenderer())
                            .setHorizontalAlignment((int)JLabel.CENTER_ALIGNMENT);
                    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                    centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                    tb1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                    for(int y = 0;y<tb1.getColumnCount();y++){
                        tb1.getColumnModel().getColumn(y).setCellRenderer(centerRenderer);
                     
                    }}
               
                con.close();
stmt.close();
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tb1.getModel();
            int rows=model.getRowCount();

            if(rows>0) {
                for(int i=0;i<rows;i++) {
                    model.removeRow(0);
                }
            }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
        if (rb1.isSelected()==true){
            st = "APPROVED";
        }

        
}//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
        if (rb2.isSelected()==true){
            st = "PENDING";
        }
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        // TODO add your handling code here:
        if (rb3.isSelected()==true){
            st = "REJECTED";
        }
    }//GEN-LAST:event_rb3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         this.getContentPane().setBackground(Color.WHITE);
      tb1.setOpaque(false);
      ((DefaultTableCellRenderer)tb1.getDefaultRenderer(Object.class)).setOpaque(false);
      jsc.setOpaque(false);
      jsc.getViewport().setOpaque(false);
      tb1.getTableHeader().setBackground(Color.WHITE);
      tb1.getTableHeader().setFont(new Font("Batang",Font.BOLD,16));
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManLoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jsc;
    private javax.swing.JLabel l1;
    public javax.swing.JButton manb;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables

}
