import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManUsr.java
 *
 * Created on Apr 4, 2018, 6:23:57 PM
 */

/**
 *
 * @author ok
 */
public class ManUsr extends javax.swing.JFrame {

    /** Creates new form ManUsr */
    public ManUsr() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        li1 = new javax.swing.JList();
        t = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        T1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b2.setFont(new java.awt.Font("Arial", 1, 12));
        b2.setText("SHOW ACCOUNTS");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 30));

        jScrollPane1.setViewportBorder(new javax.swing.border.MatteBorder(null));

        li1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Details  :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        li1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        li1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        li1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                li1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(li1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 400));

        t.setEditable(false);
        t.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t.setForeground(new java.awt.Color(0, 0, 153));
        t.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Account_ No", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        t.setOpaque(false);
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, 60));

        T3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        T3.setText("yyyy-mm-dd");
        T3.setToolTipText("ENTER YOUR DATE OF BIRTH ");
        T3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "DATE OF BIRTH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        T3.setOpaque(false);
        T3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3MouseClicked(evt);
            }
        });
        T3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T3ActionPerformed(evt);
            }
        });
        T3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                T3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                T3FocusLost(evt);
            }
        });
        getContentPane().add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 160, 60));

        T2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        T2.setToolTipText("ENTER YOUR AGE IN YEARS");
        T2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "AGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        T2.setOpaque(false);
        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });
        getContentPane().add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 150, 50));

        T6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        T6.setToolTipText("ENTER YOUR CONTACT NUMBER");
        T6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "CONTACT NUMBER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        T6.setOpaque(false);
        T6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6ActionPerformed(evt);
            }
        });
        T6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T6KeyTyped(evt);
            }
        });
        getContentPane().add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 150, 50));

        T4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        T4.setToolTipText("ENTER CITY NAME WHERE YOU RESIDE");
        T4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "CITY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        T4.setOpaque(false);
        T4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4ActionPerformed(evt);
            }
        });
        getContentPane().add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 150, 50));

        T1.setColumns(1);
        T1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        T1.setToolTipText("ENTER USER NAME");
        T1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        T1.setOpaque(false);
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 190, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 60, 50));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updt.PNG"))); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 160, 80));

        clear.setFont(new java.awt.Font("Arial", 1, 12));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 90, 40));

        b1.setFont(new java.awt.Font("Arial", 1, 12));
        b1.setText("Fetch Details");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 210, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dlt.PNG"))); // NOI18N
        jButton1.setText("DELETE");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 150, 90));
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mm.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 250, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con =null;
 Statement stmt=null;
 ResultSet rs=null;
 
 DefaultListModel dl = new DefaultListModel();
 int ac;
 String nm;

 private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        
        clear.doClick();
 try {
        Class.forName("java.sql.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmodule","root","123");
        stmt = null;
        rs = null;
        stmt = con.createStatement();
        
        String x ="Select * from account";
        rs=stmt.executeQuery(x);
        while(rs.next()) {
          ac=rs.getInt("accountno");
          nm=rs.getString("name");
         int age=rs.getInt("age");
         String st=rs.getString("state");
         String ct=rs.getString("city");
         Object s = (""+ac);
         Object r = (""+nm);
         dl.addElement("Account_no"+ s +" : " + r);
         li1.setModel(dl);
    }
         
        con.close();
stmt.close();
    }
     catch (Exception e) {
                JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
                }


}//GEN-LAST:event_b2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.WHITE);
      
    }//GEN-LAST:event_formWindowOpened

    private void li1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_li1ValueChanged
        // TODO add your handling code here:
        

       


       
   
        
    }//GEN-LAST:event_li1ValueChanged

    private void T6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T6KeyTyped
        // TODO add your handling code here:
        char kc =evt.getKeyChar();
        if (!(kc>='0' && kc<='9')|| kc==KeyEvent.VK_BACK_SPACE || kc==KeyEvent.VK_DELETE) {
            evt.consume();
        }
}//GEN-LAST:event_T6KeyTyped

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_T1ActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void T6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T6ActionPerformed

    private void T4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4ActionPerformed

    private void T3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Manager1().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
                Class.forName("java.sql.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmodule", "root", "123");
                stmt = con.createStatement();

                 String name=T1.getText();
                int age=Integer.parseInt(T2.getText());
                 String city=T4.getText();
                 String dob=T3.getText();
                 String contactno=T6.getText();
                 int a = Integer.parseInt(t.getText());
                 
                 String q1="update account set name='" + name + "',age = "+ age +",city = '" + city + "',dob = '"+ dob +"',contactno = '"+ contactno +"' where accountno='" + a + "';";
                int rowseff = stmt.executeUpdate(q1);
         String q3="Update login set name ='"+name+"'where accountno='"+a+"'";
         int roweff1 = stmt.executeUpdate(q3);
         if(rowseff==0 || roweff1 == 0)
             {
    JOptionPane.showMessageDialog(null,"SERVER PROBLEM");
         }
else
    JOptionPane.showMessageDialog(null,"ACCOUNT UPDATED");
b2.doClick();
 b2.doClick();
 t.setText("");
    T1.setText("");
    T2.setText("");
    T3.setText("");
    T4.setText("");
    T6.setText("");
    con.close();
stmt.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTING");
        }
         

                 

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        dl.removeAllElements();
        li1.setModel(dl);
}//GEN-LAST:event_clearActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:

         try {
              String l = (String)li1.getSelectedValue();
        char a = l.charAt(10);
        int b = (int)a;
        Class.forName("java.sql.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmodule","root","123");
        stmt = null;
        rs = null;
        stmt = con.createStatement();
       
        String x ="Select * from account where accountno='"+a+"'";
                rs=stmt.executeQuery(x);
                while(rs.next()) {
                     ac=rs.getInt("accountno");
                     nm=rs.getString("name");
                    int age=rs.getInt("age");
                    String ct=rs.getString("city");
                    String cnt =rs.getString("contactno");
                    String dob =rs.getString("dob");
                    t.setText(""+ac);
                    T1.setText(""+nm);
                    T2.setText(""+age);
                    T6.setText(""+cnt);
                     T4.setText(""+ct);
                     T3.setText(dob);}

            
con.close();
stmt.close();
         }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"CHOOSE FROM LIST");
                    }

}//GEN-LAST:event_b1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
Class.forName("java.sql.Driver");
con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmodule","root","123");
stmt=null;
rs=null;
stmt=con.createStatement();
int a = Integer.parseInt(t.getText());
int c =JOptionPane.showConfirmDialog(null,"Are you Sure !");
if (c==0){

String x ="delete from account where accountno="+a+"";
int rowseff = stmt.executeUpdate(x);
String y ="delete from login where accountno="+a+"";
int rowseff1 =stmt.executeUpdate(y);
if(rowseff == 0 || rowseff1 ==0)
{
    JOptionPane.showMessageDialog(this,"ACCOUNT DOES NOT EXIST");
}
else{
  JOptionPane.showMessageDialog(this,"ACCOUNT DELETED");
    b2.doClick();
    T1.setText("");
    T2.setText("");
    T3.setText("");
    T4.setText("");
    T6.setText("");
 t.setText("");


}
}
con.close();
stmt.close();
         }          catch (Exception e)
       {
        JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
         }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void T3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3MouseClicked
        // TODO add your handling code here:
        T3.setText("");
    }//GEN-LAST:event_T3MouseClicked

    private void T3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T3FocusGained
        // TODO add your handling code here:
        l2.setVisible(true);
        l2.setText("Format : yyyy-mm-dd".toUpperCase());
    }//GEN-LAST:event_T3FocusGained

    private void T3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T3FocusLost
        // TODO add your handling code here:
        l2.setVisible(false);
    }//GEN-LAST:event_T3FocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManUsr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T6;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l2;
    private javax.swing.JList li1;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables

}
